// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrO2P6LlsJqzWVEhVd_QKj3xEO6bm3tlE',
    appId: '1:226892712585:web:e77207044cf9114273d458',
    messagingSenderId: '226892712585',
    projectId: 'virtual-study-buddy-179e4',
    authDomain: 'virtual-study-buddy-179e4.firebaseapp.com',
    storageBucket: 'virtual-study-buddy-179e4.appspot.com',
    measurementId: 'G-PL6759CS4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh40ShIOPeMkcBnaq9DMyWnAXt-hPk7eg',
    appId: '1:226892712585:android:2cc5dc729e70560e73d458',
    messagingSenderId: '226892712585',
    projectId: 'virtual-study-buddy-179e4',
    storageBucket: 'virtual-study-buddy-179e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuurkeDYQSF5QqQCnJZoeFffvXzABm64k',
    appId: '1:226892712585:ios:a34d341e72c3ab7773d458',
    messagingSenderId: '226892712585',
    projectId: 'virtual-study-buddy-179e4',
    storageBucket: 'virtual-study-buddy-179e4.appspot.com',
    iosBundleId: 'com.example.virtualStudyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuurkeDYQSF5QqQCnJZoeFffvXzABm64k',
    appId: '1:226892712585:ios:a34d341e72c3ab7773d458',
    messagingSenderId: '226892712585',
    projectId: 'virtual-study-buddy-179e4',
    storageBucket: 'virtual-study-buddy-179e4.appspot.com',
    iosBundleId: 'com.example.virtualStudyBuddy',
  );
}
